services:
  nginx:
    build:
      context: ./nginx  # Path to your custom NGINX Dockerfile and nginx.conf
    ports:
      - "80:80"  # Expose only port 80 externally
    depends_on:
      - python-server
      - node-server
    networks:
      - app-network

  python-server:
    build:
      context: ./  # Path to your Python Flask application
      dockerfile: Dockerfile  # Dockerfile for your Flask app
    networks:
      - app-network

  node-server:
    build:
      context: ./pdf-converter  # Path to your Node.js PDF converter
      dockerfile: Dockerfile  # Dockerfile for your Node.js app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge