services:
  nginx:
    image: dockerteamstl/nginx:latest  # Pull the NGINX image from Docker Hub
    ports:
      - "80:80"  # Expose only port 80 externally
    depends_on:
      - python-server
      - node-server
    networks:
      - app-network

  python-server:
    image: dockerteamstl/text-processor-python-server:latest  # Pull the Python server image from Docker Hub
    networks:
      - app-network

  node-server:
    image: dockerteamstl/text-processor-node-server:latest  # Pull the Node.js server image from Docker Hub
    networks:
      - app-network

networks:
  app-network:
    driver: bridge